#!/usr/bin/env python3
"""Generate the authoritative tool docs FROM the registry.

Four contradictory tool counts once coexisted across API.md/README/live
server/registry. This script makes the registry the single source: both
the summary table AND the per-tool parameter reference in docs/API.md
are generated, and --check fails CI when either drifts.

Usage:
    python scripts/dump_tool_table.py           # print the markdown table
    python scripts/dump_tool_table.py --write   # update docs/API.md in place
    python scripts/dump_tool_table.py --check   # exit 1 if docs drifted
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from ewsmcp.tools import calendar_people, mail_read, tasks, writes  # noqa: E402
from ewsmcp.tools.base import CLASS_TIER  # noqa: E402

API_MD = Path(__file__).resolve().parents[1] / "docs" / "API.md"
START = "<!-- TOOL_TABLE_START (generated by scripts/dump_tool_table.py) -->"
END = "<!-- TOOL_TABLE_END -->"
DETAILS_START = "<!-- TOOL_DETAILS_START (generated by scripts/dump_tool_table.py) -->"
DETAILS_END = "<!-- TOOL_DETAILS_END -->"


def _packs():
    return [
        ("mail-read", mail_read.TOOLS),
        ("calendar / people / status", calendar_people.TOOLS),
        ("tasks / waiting-on", tasks.TOOLS),
        ("writes", writes.TOOLS),
        ("semantic (only when EWS_SEMANTIC_INDEX != none)",
         mail_read.SEMANTIC_TOOLS),
    ]


def _first_sentence(text: str) -> str:
    text = " ".join((text or "").split())
    for stop in (". ", "; "):
        idx = text.find(stop)
        if idx > 0:
            return text[: idx + 1].rstrip()
    return text[:140]


def build_table() -> str:
    packs = _packs()
    core = sum(len(t) for _n, t in packs[:4])
    lines = [
        f"**{core} tools** in the default registry "
        f"(+{len(mail_read.SEMANTIC_TOOLS)} with the semantic tier). "
        "Capability tiers: read ⊂ draft ⊂ full — a tool is available when "
        "the server tier is at or above its minimum.",
        "",
        "| tool | class | min tier | what it does |",
        "|---|---|---|---|",
    ]
    for _pack_name, specs in packs:
        for spec in specs:
            lines.append(
                f"| `{spec.name}` | {spec.side_effect_class} "
                f"| {CLASS_TIER.get(spec.side_effect_class, 'draft')} "
                f"| {_first_sentence(spec.description)} |"
            )
    return "\n".join(lines)


def _md_cell(text: str) -> str:
    return " ".join((text or "").split()).replace("|", "\\|")


def _schema_rows(schema) -> list:
    props = (schema or {}).get("properties", {}) or {}
    required = set((schema or {}).get("required", []) or [])
    rows = []
    for name, prop in props.items():
        typ = prop.get("type", "any")
        if isinstance(typ, list):
            typ = "/".join(str(t) for t in typ)
        desc = _md_cell(prop.get("description", ""))
        extras = []
        if "enum" in prop:
            extras.append("one of: " + ", ".join(f"`{v}`" for v in prop["enum"]))
        if "default" in prop:
            extras.append(f"default `{prop['default']}`")
        if extras:
            desc = (desc + " " if desc else "") + "(" + "; ".join(extras) + ")"
        rows.append(
            f"| `{name}` | {typ} "
            f"| {'yes' if name in required else 'no'} | {desc} |"
        )
    return rows


def build_details() -> str:
    lines = []
    for pack_name, specs in _packs():
        lines.append(f"### {pack_name}")
        lines.append("")
        for spec in specs:
            tier = CLASS_TIER.get(spec.side_effect_class, "draft")
            lines.append(
                f"#### `{spec.name}` — {spec.side_effect_class} "
                f"(min tier: {tier})"
            )
            lines.append("")
            lines.append(_md_cell(spec.description).replace("\\|", "|"))
            lines.append("")
            if callable(spec.confirm):
                lines.append(
                    "> Two-phase confirm for some argument combinations: the "
                    "first call returns a preview + `confirm_token`; repeat "
                    "the call with the token to execute.")
                lines.append("")
            elif spec.confirm:
                lines.append(
                    "> Two-phase confirm: the first call returns a preview + "
                    "`confirm_token`; repeat the call with the token to "
                    "execute.")
                lines.append("")
            rows = _schema_rows(spec.input_schema)
            if rows:
                lines.append("| parameter | type | required | description |")
                lines.append("|---|---|---|---|")
                lines.extend(rows)
            else:
                lines.append("_No parameters._")
            lines.append("")
    return "\n".join(lines).rstrip()


def _replace_block(content: str, start: str, end: str, body: str):
    if start not in content or end not in content:
        return None
    head, _, rest = content.partition(start)
    _, _, tail = rest.partition(end)
    return f"{head}{start}\n{body}\n{end}{tail}"


def main() -> int:
    table = build_table()
    if len(sys.argv) == 1:
        print(table)
        return 0
    if not API_MD.exists():
        print(f"missing {API_MD}")
        return 2
    content = API_MD.read_text(encoding="utf-8")
    regenerated = _replace_block(content, START, END, table)
    if regenerated is not None:
        regenerated = _replace_block(
            regenerated, DETAILS_START, DETAILS_END, build_details())
    if regenerated is None:
        print(f"generated-block markers missing in {API_MD}")
        return 2
    if sys.argv[1] == "--write":
        API_MD.write_text(regenerated, encoding="utf-8", newline="\n")
        print(f"updated {API_MD}")
        return 0
    if sys.argv[1] == "--check":
        if content != regenerated:
            print("docs/API.md DRIFTED from the registry — "
                  "run scripts/dump_tool_table.py --write")
            return 1
        print("docs/API.md matches the registry")
        return 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main())
